homes/urls.py
from django.urls import path

from homes.views import (
    HomeDetailView,
    HomeListView,
    HomeCreateView,
    HomeDeleteView,
    HomeUpdateView,
    RoofCreateView,
    RoofUpdateView,
    RoofDeleteView,
    ApplianceCreateView,
    ApplianceUpdateView,
    ApplianceDeleteView,
)

urlpatterns = [
    path("", HomeListView.as_view(), name="home_list"),
    path("<int:pk>/", HomeDetailView.as_view(), name="home_details"),
    path("create/", HomeCreateView.as_view(), name="home_create"),
    path("<int:pk>/update/", HomeUpdateView.as_view(), name="home_update"),
    path("<int:pk>/delete/", HomeDeleteView.as_view(), name="home_delete"),
    path("roof/create", RoofCreateView.as_view(), name="roof_create"),
    path("roof/<int:pk>/update/", RoofUpdateView.as_view(), name="roof_update"),
    path("roof/<int:pk>/delete/", RoofDeleteView.as_view(), name="roof_delete"),
    path("appliance/create", ApplianceCreateView.as_view(), name="appliance_create"),
    path("appliance/<int:pk>/update/", ApplianceUpdateView.as_view(), name="appliance_update"),
    path("appliance/<int:pk>/delete/", ApplianceDeleteView.as_view(), name="appliance_delete"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path("", RedirectView.as_view(pattern_name="home_list"), name="home"),
    path('admin/', admin.site.urls),
    path("home/", include("homes.urls")),
    path("accounts/", include("accounts.urls")),
    path("maintenance/", include("maintenance.urls")),
    path("serviceproviders/", include("service_providers.urls")),
]

service_providers/urls.py
from django.urls import path

from service_providers.views import (
    ServiceProviderListView,
    ServiceProviderDetailView,
    ServiceProviderCreateView,
    ServiceProviderUpdateView,
    ServiceProvdiersDeleteView
)

urlpatterns = [
    path("", ServiceProviderListView.as_view(), name="service_providers_list"),
    path("<int:pk>/", ServiceProviderDetailView.as_view(), name="service_providers_details"),
    path("create/", ServiceProviderCreateView.as_view(), name="service_providers_create"),
    path("<int:pk>/update/", ServiceProviderUpdateView.as_view(), name="service_providers_update"),
    path("<int:pk>/delete/", ServiceProvdiersDeleteView.as_view(), name="service_providers_delete"),
]

service_providers/models.py
from django.db import models
from django.contrib.auth.models import User

class ServiceProvider(models.Model):
    name = models.CharField(max_length=255)
    company = models.CharField(max_length=255, null=True, blank=True)
    SERVICE_PROVIDER_TYPE = (
    ("Electrician", "Electrician"),
    ("Plumber", "Plumber"),
    ("Landscaper", "Landscaper"),
    ("Handyman", "Handyman"),
    ("Appliance Repair", "Appliance Repair"),
    ("General Contractor", "General Contractor"),
    ("Pest", "Pest"),
    ("Painter", "Painter"),
    ("HVAC Tech", "HVAC Tech"),
    ("Other", "Other"), 
    )
    type = models.CharField(max_length=40, null=True, blank=True, choices=SERVICE_PROVIDER_TYPE)
    phone = models.IntegerField(null=True, blank=True)
    email = models.CharField(max_length=255, null=True, blank=True)
    website = models.CharField(max_length=255, null=True, blank=True)
    notes = models.TextField(null=True, blank=True)
    added_by = models.ForeignKey(User, related_name="servicer_providers", on_delete=models.CASCADE)

    def __str__(self):
        return self.name

service_providers/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.detail import DetailView

from django.urls import reverse_lazy  # reverse
from service_providers.models import ServiceProvider

class ServiceProviderListView(LoginRequiredMixin, ListView):
    model = ServiceProvider
    template_name = "service_provider_list.html"

    def get_queryset(self):
        return ServiceProvider.objects.filter(added_by=self.request.user)

class ServiceProviderDetailView(LoginRequiredMixin, DetailView):
    model = ServiceProvider
    template_name = "service_provider_details.html"

    def get_queryset(self):
        return ServiceProvider.objects.filter(added_by=self.request.user)

class ServiceProviderCreateView(LoginRequiredMixin, CreateView):
    model = ServiceProvider
    template_name = "service_provider_create.html"
    fields = ["name", "company", "type", "phone", "email", "website", "notes"]
      
    def form_valid(self, form):
        item = form.save(commit=False)
        item.added_by = self.request.user
        item.save()
        return redirect("service_providers_list")


class ServiceProviderUpdateView(UpdateView):
    model = ServiceProvider
    template_name = "service_providers_update.html"
    fields = ["name", "company", "type", "phone", "email", "website", "notes"]
    success_url = reverse_lazy("service_providers_list")

class ServiceProvdiersDeleteView(DeleteView):
    model = ServiceProvider
    template_name = "service_provider_delete.html"
    success_url = reverse_lazy("service_providers_list")

service_providers/templates/service_provider_create.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div>
            <h1>Add new Service Provider</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Create</button>
            </form>

        </div>
    </main>



{% endblock content %}

service_providers/templates/service_provider_delete.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div>
            <h1>Are you sure you want to delete {{serviceprovider.name}}?</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Confirm</button>
            </form>

        </div>
    </main>



{% endblock content %}

service_providers/templates/service_provider_details.html
{% extends 'base.html' %}

{% block content %}
    <main>
            <h1>{{ serviceprovider.name }}</h1>
                <p> Company: {{ serviceprovider.company }}</p>
                <p>Type: {{ serviceprovider.type }}</p>
                <p>Phone: {{ serviceprovider.phone}}</p>
                <p>Email: {{ serviceprovider.email}}</p>
                <p>Website: {{ serviceprovider.website}}</p>
                <p>Notes: {{ serviceprovider.notes}}</p>
                <p><form method="get" action="{% url 'service_providers_update' serviceprovider.id %}">
                    <button type="submit">Update</button>
                </form></p>
                <p><form method="get" action="{% url 'service_providers_delete' serviceprovider.id %}">
                    <button type="submit">Delete</button>
                </form></p>
    </main>
{% endblock content %}

service_providers/templates/service_provider_list.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div>
            <h1>My Service Providers</h1>
            <p>Add Service Provider:</p>
            <p><form method="get" action="{% url 'service_providers_create' %}">
                <button type="submit">Create</button>
            </form></p>
            {% if serviceprovider_list.all|length > 0 %}
                <table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Company</th>
                            <th>Type</th>
                            <th>Phone</th>
                            <th>Email</th>
                            <th>Website</th>
                            <th>Notes</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for provider in serviceprovider_list.all %}
                            <tr>
                                <td><a href="{% url 'service_providers_details' provider.pk %}">{{provider.name}}</td></a>
                                <td>{{provider.company}}</td>
                                <td>{{provider.type}}</td>
                                <td>{{provider.phone}}</td>
                                <td>{{provider.email}}</td>
                                <td>{{provider.website}}</td>
                                <td>{{provider.notes}}</td>
                            </tr>
                            </tbody>
                        {% endfor %}
                </table>
            {% else %}
                <p>You have no service providers yet.</p>
            {% endif %}
    </div>
    </main>
{% endblock content %}

<p><a href="{% url 'todo_list_update' todolist.pk %}">Edit</a></p>
<p><a href="{% url 'todo_list_delete' todolist.pk %}">Delete</a></p>

service_providers/templates/service_providers_update.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div>
            <h1>Update Service Provider</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Update</button>
            </form>

        </div>
    </main>



{% endblock content %}